### ISSUE TITLE
GetEvents fails with event type "SIGNER_NAME_CHANGED_BY_SIGNER"

### ISSUE THREAD

**Issue by moto-geek** [adobe-sign/AdobeSignCSharpSDK#10]
**Expected Behaviour**

Complete GetEvents

**Actual Behaviour**

GetEvents missing Enum SIGNER_NAME_CHANGED_BY_SIGNER, return null exception

**Reproduce Scenario (including but not limited to)**

Using AdobeSign API v5 or v6. GetEvents call

Was added Jun 2022.  This SDK was not updated.
https://helpx.adobe.com/sign/using/technical-notifications.html 

**Steps to Reproduce**

Using AdobeSign API v5 or v6. GetEvents call

**Platform and Version**

ASP.NET C# .Net Framework project calling SDK code Using AdobeSign API v5 or v6. GetEvents call

**Sample Code that illustrates the problem**

GetEvents method

**Logs taken while reproducing problem**

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> AdobeSign.RESTApi.Client.ApiException: Error converting value "SIGNER_NAME_CHANGED_BY_SIGNER" to type 'System.Nullable`1[AdobeSign.RESTApi.model.agreements.AgreementEvent+TypeEnum]'. Path 'events[2].type', line 1, position 1188.
   at AdobeSign.RESTApi.Client.ApiClient.Deserialize(IRestResponse response, Type type) in C:\xxxxxxxxx\AdobeSignCSharpSDK\src\VernAdobeSign.RESTApi\Client\ApiClient.cs:line 346
   at AdobeSign.RESTApi.Api.AgreementsApi.GetEventsWithHttpInfo(String authorization, String agreementId, String xApiUser, String xOnBehalfOfUser, String ifNoneMatch) in C:\xxxxxxxxxx\AdobeSignCSharpSDK\src\VernAdobeSign.RESTApi\Api\AgreementsApi.cs:line 6442

**Comment by moto-geek** [comment]
Add fix to pull request 

https://github.com/moto-geek/AdobeSignCSharpSDK/pull/1/commits/45aabdb16e14dc5e7106de12319a44a1dd83fd3d
